import type {
  BuilderProfile,
  Repository,
  CollaborationGraph,
  CollaboratorRecommendation,
  ActivityEvent,
  AnalysisJob,
} from './types';

// ============================================================
// Mock Data Layer - Simulates backend responses
// Replace with real API calls when backend is connected
// ============================================================

export const MOCK_BUILDER: BuilderProfile = {
  id: 'builder-001',
  wallet_address: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
  github_username: 'alexchen',
  github_avatar: null,
  display_name: 'Alex Chen',
  bio: 'Full-stack builder. Solana ecosystem contributor. Open source advocate.',
  ai_summary:
    'Alex is a high-velocity full-stack developer with deep expertise in Rust and TypeScript. Their repositories demonstrate strong architectural thinking, particularly in async systems and blockchain infrastructure. Consistent commit patterns over 18 months suggest sustained engagement. Notable strength in DeFi protocol development with evidence of production deployments. Collaboration patterns indicate a lead-developer role with mentoring tendencies.',
  skill_tags: [
    { name: 'Rust', category: 'language', confidence: 0.95, inferred_from: ['solana-amm', 'anchor-escrow'] },
    { name: 'TypeScript', category: 'language', confidence: 0.92, inferred_from: ['graphite-ui', 'defi-dashboard'] },
    { name: 'Solana', category: 'framework', confidence: 0.9, inferred_from: ['solana-amm', 'anchor-escrow', 'spl-tools'] },
    { name: 'React', category: 'framework', confidence: 0.88, inferred_from: ['graphite-ui', 'defi-dashboard'] },
    { name: 'DeFi', category: 'domain', confidence: 0.87, inferred_from: ['solana-amm', 'defi-dashboard'] },
    { name: 'Systems Design', category: 'pattern', confidence: 0.85, inferred_from: ['solana-amm', 'event-pipeline'] },
    { name: 'Anchor', category: 'tool', confidence: 0.83, inferred_from: ['anchor-escrow', 'solana-amm'] },
    { name: 'Node.js', category: 'framework', confidence: 0.8, inferred_from: ['event-pipeline', 'api-gateway'] },
    { name: 'PostgreSQL', category: 'tool', confidence: 0.75, inferred_from: ['event-pipeline', 'defi-dashboard'] },
    { name: 'WebSocket', category: 'pattern', confidence: 0.72, inferred_from: ['defi-dashboard', 'event-pipeline'] },
  ],
  reputation: {
    overall_score: 82,
    dimensions: [
      {
        dimension: 'technical_depth',
        score: 88,
        confidence: 0.91,
        signals: ['Rust + TS proficiency', 'Low-level Solana program design', 'Custom AMM implementation'],
        trend: 'rising',
      },
      {
        dimension: 'execution_ability',
        score: 85,
        confidence: 0.88,
        signals: ['6 deployed projects', 'CI/CD detected', 'Production deployment links'],
        trend: 'stable',
      },
      {
        dimension: 'collaboration_quality',
        score: 76,
        confidence: 0.82,
        signals: ['12 unique collaborators', 'PR review patterns', 'Issue management'],
        trend: 'rising',
      },
      {
        dimension: 'consistency',
        score: 79,
        confidence: 0.85,
        signals: ['18-month active streak', 'Regular commit patterns', 'Sustained project maintenance'],
        trend: 'stable',
      },
      {
        dimension: 'innovation',
        score: 72,
        confidence: 0.78,
        signals: ['Novel AMM design', 'Custom tooling', 'Experimental repo detected'],
        trend: 'rising',
      },
    ],
    last_computed: '2026-05-08T14:30:00Z',
    signal_count: 247,
  },
  github_stats: {
    total_repos: 24,
    total_stars: 342,
    total_forks: 89,
    total_commits: 1847,
    top_languages: [
      { language: 'Rust', percentage: 38, bytes: 245000, color: '#dea584' },
      { language: 'TypeScript', percentage: 32, bytes: 208000, color: '#3178c6' },
      { language: 'JavaScript', percentage: 12, bytes: 78000, color: '#f1e05a' },
      { language: 'Solidity', percentage: 8, bytes: 52000, color: '#AA6746' },
      { language: 'Python', percentage: 6, bytes: 39000, color: '#3572A5' },
      { language: 'Other', percentage: 4, bytes: 26000, color: '#6e7681' },
    ],
    contribution_streak: 47,
    active_days_last_year: 218,
  },
  analysis_status: 'completed',
  created_at: '2026-01-15T10:00:00Z',
  updated_at: '2026-05-08T14:30:00Z',
};

export const MOCK_REPOSITORIES: Repository[] = [
  {
    id: 'repo-001',
    github_id: 100001,
    name: 'solana-amm',
    full_name: 'alexchen/solana-amm',
    description: 'Concentrated liquidity AMM built on Solana with custom curve implementations',
    url: 'https://github.com/alexchen/solana-amm',
    homepage: 'https://amm.alexchen.dev',
    stars: 127,
    forks: 34,
    watchers: 89,
    language: 'Rust',
    languages: { Rust: 180000, TypeScript: 45000, JavaScript: 12000 },
    topics: ['solana', 'defi', 'amm', 'rust', 'anchor'],
    is_fork: false,
    created_at: '2025-06-20T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
    pushed_at: '2026-05-01T00:00:00Z',
    analysis_status: 'completed',
    analysis: {
      id: 'analysis-001',
      repo_id: 'repo-001',
      architecture_complexity: 9,
      code_quality_signals: 8,
      execution_maturity: 8,
      originality_score: 9,
      inferred_skills: ['Rust', 'Solana', 'DeFi', 'AMM Design', 'Math Libraries'],
      probable_domains: ['DeFi', 'Blockchain Infrastructure', 'Financial Engineering'],
      builder_summary: 'Production-grade AMM with novel concentrated liquidity implementation. Demonstrates deep Solana expertise and financial engineering knowledge.',
      key_patterns: ['Custom math library', 'Anchor framework', 'Fee tier system', 'Oracle integration'],
      deployment_detected: true,
      test_coverage_signals: 'comprehensive',
      analyzed_at: '2026-05-02T00:00:00Z',
    },
  },
  {
    id: 'repo-002',
    github_id: 100002,
    name: 'defi-dashboard',
    full_name: 'alexchen/defi-dashboard',
    description: 'Real-time DeFi portfolio tracker with WebSocket feeds and analytics',
    url: 'https://github.com/alexchen/defi-dashboard',
    homepage: 'https://dashboard.alexchen.dev',
    stars: 89,
    forks: 23,
    watchers: 45,
    language: 'TypeScript',
    languages: { TypeScript: 120000, CSS: 25000, JavaScript: 8000 },
    topics: ['defi', 'dashboard', 'react', 'typescript', 'websocket'],
    is_fork: false,
    created_at: '2025-09-10T00:00:00Z',
    updated_at: '2026-04-28T00:00:00Z',
    pushed_at: '2026-04-28T00:00:00Z',
    analysis_status: 'completed',
    analysis: {
      id: 'analysis-002',
      repo_id: 'repo-002',
      architecture_complexity: 7,
      code_quality_signals: 8,
      execution_maturity: 7,
      originality_score: 6,
      inferred_skills: ['React', 'TypeScript', 'WebSocket', 'Data Visualization', 'State Management'],
      probable_domains: ['Frontend', 'DeFi', 'Data Visualization'],
      builder_summary: 'Well-structured real-time dashboard with clean component architecture and efficient data flow patterns.',
      key_patterns: ['Custom hooks', 'WebSocket management', 'Recharts integration', 'Zustand state'],
      deployment_detected: true,
      test_coverage_signals: 'moderate',
      analyzed_at: '2026-04-29T00:00:00Z',
    },
  },
  {
    id: 'repo-003',
    github_id: 100003,
    name: 'anchor-escrow',
    full_name: 'alexchen/anchor-escrow',
    description: 'Trustless escrow program for Solana with multi-sig support',
    url: 'https://github.com/alexchen/anchor-escrow',
    homepage: null,
    stars: 56,
    forks: 18,
    watchers: 32,
    language: 'Rust',
    languages: { Rust: 65000, TypeScript: 22000 },
    topics: ['solana', 'anchor', 'escrow', 'defi'],
    is_fork: false,
    created_at: '2025-11-05T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
    pushed_at: '2026-03-15T00:00:00Z',
    analysis_status: 'completed',
    analysis: {
      id: 'analysis-003',
      repo_id: 'repo-003',
      architecture_complexity: 6,
      code_quality_signals: 9,
      execution_maturity: 7,
      originality_score: 5,
      inferred_skills: ['Anchor', 'Solana', 'Security Patterns', 'Multi-sig'],
      probable_domains: ['DeFi', 'Security', 'Smart Contracts'],
      builder_summary: 'Clean escrow implementation with strong security patterns. Multi-sig support shows understanding of production safety requirements.',
      key_patterns: ['PDA derivation', 'Time-lock mechanisms', 'Multi-sig validation', 'Comprehensive tests'],
      deployment_detected: false,
      test_coverage_signals: 'comprehensive',
      analyzed_at: '2026-03-16T00:00:00Z',
    },
  },
  {
    id: 'repo-004',
    github_id: 100004,
    name: 'event-pipeline',
    full_name: 'alexchen/event-pipeline',
    description: 'Scalable event-driven data pipeline with backpressure handling',
    url: 'https://github.com/alexchen/event-pipeline',
    homepage: null,
    stars: 41,
    forks: 8,
    watchers: 19,
    language: 'TypeScript',
    languages: { TypeScript: 95000, JavaScript: 5000 },
    topics: ['event-driven', 'pipeline', 'nodejs', 'typescript'],
    is_fork: false,
    created_at: '2025-08-01T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
    pushed_at: '2026-02-20T00:00:00Z',
    analysis_status: 'analyzing',
    analysis: undefined,
  },
  {
    id: 'repo-005',
    github_id: 100005,
    name: 'spl-tools',
    full_name: 'alexchen/spl-tools',
    description: 'CLI toolkit for SPL token operations and metadata management',
    url: 'https://github.com/alexchen/spl-tools',
    homepage: null,
    stars: 29,
    forks: 6,
    watchers: 15,
    language: 'Rust',
    languages: { Rust: 42000 },
    topics: ['solana', 'spl', 'cli', 'rust', 'tools'],
    is_fork: false,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
    pushed_at: '2026-04-10T00:00:00Z',
    analysis_status: 'pending',
    analysis: undefined,
  },
];

export const MOCK_GRAPH: CollaborationGraph = {
  nodes: [
    { id: 'n1', label: 'Alex Chen', type: 'builder', score: 82, size: 28 },
    { id: 'n2', label: 'Sarah Kim', type: 'builder', score: 78, size: 22 },
    { id: 'n3', label: 'Dev Patel', type: 'builder', score: 71, size: 20 },
    { id: 'n4', label: 'Maria Santos', type: 'builder', score: 85, size: 26 },
    { id: 'n5', label: 'James Liu', type: 'builder', score: 68, size: 18 },
    { id: 'n6', label: 'Priya Sharma', type: 'builder', score: 74, size: 20 },
    { id: 'n7', label: 'Tom Wilson', type: 'builder', score: 66, size: 16 },
    { id: 'n8', label: 'solana-amm', type: 'repository', size: 20 },
    { id: 'n9', label: 'defi-dashboard', type: 'repository', size: 16 },
    { id: 'n10', label: 'anchor-escrow', type: 'repository', size: 14 },
    { id: 'n11', label: 'Solana Labs', type: 'organization', size: 24 },
    { id: 'n12', label: 'DeFi', type: 'skill', size: 18 },
    { id: 'n13', label: 'Rust', type: 'skill', size: 16 },
  ],
  edges: [
    { id: 'e1', source: 'n1', target: 'n2', weight: 0.85, type: 'collaborated', label: '12 shared commits' },
    { id: 'e2', source: 'n1', target: 'n3', weight: 0.65, type: 'collaborated', label: '6 shared commits' },
    { id: 'e3', source: 'n1', target: 'n4', weight: 0.72, type: 'collaborated', label: '8 PRs reviewed' },
    { id: 'e4', source: 'n2', target: 'n4', weight: 0.58, type: 'collaborated' },
    { id: 'e5', source: 'n1', target: 'n8', weight: 0.95, type: 'contributed' },
    { id: 'e6', source: 'n2', target: 'n8', weight: 0.7, type: 'contributed' },
    { id: 'e7', source: 'n1', target: 'n9', weight: 0.9, type: 'contributed' },
    { id: 'e8', source: 'n5', target: 'n9', weight: 0.5, type: 'forked' },
    { id: 'e9', source: 'n1', target: 'n10', weight: 0.85, type: 'contributed' },
    { id: 'e10', source: 'n3', target: 'n10', weight: 0.6, type: 'contributed' },
    { id: 'e11', source: 'n1', target: 'n11', weight: 0.4, type: 'contributed' },
    { id: 'e12', source: 'n4', target: 'n11', weight: 0.6, type: 'contributed' },
    { id: 'e13', source: 'n1', target: 'n12', weight: 0.87, type: 'skill_match' },
    { id: 'e14', source: 'n4', target: 'n12', weight: 0.82, type: 'skill_match' },
    { id: 'e15', source: 'n1', target: 'n13', weight: 0.95, type: 'skill_match' },
    { id: 'e16', source: 'n6', target: 'n8', weight: 0.45, type: 'starred' },
    { id: 'e17', source: 'n7', target: 'n9', weight: 0.35, type: 'forked' },
    { id: 'e18', source: 'n5', target: 'n6', weight: 0.52, type: 'collaborated' },
    { id: 'e19', source: 'n6', target: 'n3', weight: 0.48, type: 'collaborated' },
  ],
  clusters: [
    { id: 'c1', label: 'DeFi Builders', node_ids: ['n1', 'n2', 'n4'], dominant_skill: 'DeFi' },
    { id: 'c2', label: 'Frontend Devs', node_ids: ['n5', 'n7'], dominant_skill: 'React' },
    { id: 'c3', label: 'Systems Engineers', node_ids: ['n3', 'n6'], dominant_skill: 'Rust' },
  ],
};

export const MOCK_RECOMMENDATIONS: CollaboratorRecommendation[] = [
  {
    builder: {
      ...MOCK_BUILDER,
      id: 'builder-002',
      display_name: 'Maria Santos',
      github_username: 'mariasantos',
      wallet_address: '9yKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgBbV',
      ai_summary: 'Expert in DeFi protocol design with strong Rust skills. Complements your frontend capabilities.',
      reputation: { ...MOCK_BUILDER.reputation, overall_score: 85 },
    },
    match_score: 92,
    reasons: ['Strong DeFi overlap', 'Complementary backend skills', 'Active in Solana ecosystem'],
    complementary_skills: ['Protocol Design', 'Auditing', 'Tokenomics'],
    shared_interests: ['DeFi', 'Solana', 'Open Source'],
  },
  {
    builder: {
      ...MOCK_BUILDER,
      id: 'builder-003',
      display_name: 'Sarah Kim',
      github_username: 'sarahkim',
      wallet_address: '5aKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgCcW',
      ai_summary: 'Data infrastructure specialist with ML pipeline experience. Strong in Python and systems design.',
      reputation: { ...MOCK_BUILDER.reputation, overall_score: 78 },
    },
    match_score: 84,
    reasons: ['ML infrastructure expertise', 'Shared systems design interest', 'Active contributor'],
    complementary_skills: ['ML Pipelines', 'Data Engineering', 'Python'],
    shared_interests: ['Infrastructure', 'Data Systems', 'Tooling'],
  },
  {
    builder: {
      ...MOCK_BUILDER,
      id: 'builder-004',
      display_name: 'Dev Patel',
      github_username: 'devpatel',
      wallet_address: '3bKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgDdX',
      ai_summary: 'Security researcher and smart contract auditor. Brings critical security perspective to protocol development.',
      reputation: { ...MOCK_BUILDER.reputation, overall_score: 71 },
    },
    match_score: 76,
    reasons: ['Security audit skills', 'Solana smart contract experience', 'Complements development velocity'],
    complementary_skills: ['Security Auditing', 'Formal Verification', 'Penetration Testing'],
    shared_interests: ['Smart Contracts', 'Security', 'Solana'],
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: 'evt-001',
    type: 'repo_analyzed',
    title: 'Repository analyzed',
    description: 'solana-amm analysis completed with 9/10 architecture score',
    timestamp: '2026-05-08T14:30:00Z',
  },
  {
    id: 'evt-002',
    type: 'reputation_computed',
    title: 'Reputation updated',
    description: 'Overall score increased to 82 (+3 from last computation)',
    timestamp: '2026-05-08T14:25:00Z',
  },
  {
    id: 'evt-003',
    type: 'collaborator_found',
    title: 'New collaborator match',
    description: 'Maria Santos identified as 92% skill complement match',
    timestamp: '2026-05-07T10:15:00Z',
  },
  {
    id: 'evt-004',
    type: 'repo_analyzed',
    title: 'Repository analyzed',
    description: 'defi-dashboard analysis completed with 7/10 architecture score',
    timestamp: '2026-05-06T16:45:00Z',
  },
  {
    id: 'evt-005',
    type: 'github_connected',
    title: 'GitHub connected',
    description: 'GitHub account alexchen linked successfully. 24 repositories discovered.',
    timestamp: '2026-05-05T09:00:00Z',
  },
  {
    id: 'evt-006',
    type: 'profile_updated',
    title: 'Profile created',
    description: 'Builder profile initialized with wallet authentication',
    timestamp: '2026-05-05T08:55:00Z',
  },
];

export const MOCK_JOBS: AnalysisJob[] = [
  {
    id: 'job-001',
    builder_id: 'builder-001',
    type: 'repo_analysis',
    status: 'processing',
    progress: 67,
    started_at: '2026-05-08T14:20:00Z',
    completed_at: null,
  },
  {
    id: 'job-002',
    builder_id: 'builder-001',
    type: 'github_ingest',
    status: 'completed',
    progress: 100,
    started_at: '2026-05-08T14:00:00Z',
    completed_at: '2026-05-08T14:15:00Z',
  },
  {
    id: 'job-003',
    builder_id: 'builder-001',
    type: 'reputation_compute',
    status: 'queued',
    progress: 0,
    started_at: null,
    completed_at: null,
  },
];

// Dimension display metadata
export const DIMENSION_META: Record<string, { label: string; description: string; icon: string }> = {
  technical_depth: {
    label: 'Technical Depth',
    description: 'Mastery of languages, frameworks, and low-level systems',
    icon: 'Cpu',
  },
  execution_ability: {
    label: 'Execution Ability',
    description: 'Track record of shipping, deploying, and maintaining projects',
    icon: 'Rocket',
  },
  collaboration_quality: {
    label: 'Collaboration',
    description: 'Team dynamics, PR reviews, and community contribution patterns',
    icon: 'Users',
  },
  consistency: {
    label: 'Consistency',
    description: 'Sustained engagement, commit frequency, and project maintenance',
    icon: 'Activity',
  },
  innovation: {
    label: 'Innovation',
    description: 'Novel approaches, experimental projects, and creative problem solving',
    icon: 'Lightbulb',
  },
};
